# Default values for file-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.cn-hangzhou.aliyuncs.com/choerodon-framework/file-service
  pullPolicy: Always

preJob:
  timeout: 300
  image: registry.cn-hangzhou.aliyuncs.com/choerodon-tools/dbtool:0.6.2
  preConfig:
    enable: true
    configFile: application.yml
    configType: k8s
    registerHost: http://register-server:8000
    datasource:
      url: jdbc:mysql://localhost:3306/manager_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: username
      password: password

deployment:
  managementPort: 9091

env:
  open:
    SPRING_CLOUD_CONFIG_ENABLED: true
    SPRING_CLOUD_CONFIG_URI: http://register-server.io-choerodon:8000/
    EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://register-server.io-choerodon:8000/eureka/
    MINIO_ENDPOINT: http:127.0.0.1:8888/minio
    MINIO_ACCESSKEY: accessKey
    MINIO_SECRETKEY: secretKey
    # skywalking 代理端配置
#    SKYWALKING_OPTS: >-
#      -javaagent:/agent/skywalking-agent.jar
#      -Dskywalking.agent.application_code=file-service
#      -Dskywalking.agent.sample_n_per_3_secs=-1
#      -Dskywalking.collector.backend_service=oap.skywalking:11800
service:
  enable: false
  type: ClusterIP
  port: 9090
  name: file-service

metrics:
  path: /prometheus
  group: spring-boot

logs:
  parser: spring-boot

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources,such as Minikube. If you do want to specify resources,uncomment the following
  # lines,adjust them as necessary,and remove the curly braces after 'resources:'.
  limits:
    # cpu: 100m
    memory: 2Gi
  requests:
    # cpu: 100m
    memory: 1Gi